### PR TITLE
Store type mappings for ComponentActivator in Dictionary

### PR DESCRIPTION
**Pull request by FStolte**
This PR deals with #2165 and improves on #2167.

The component instantiation inside the ComponentActivator is now completely done by using `Activator.CreateInstance()` instead of the ServiceProvider. This circumvents the problem that the ServiceProvider holds references to disposable transient services and keeps them from being GCed in a timely manner.

To replace the ServiceProvider registrations of the provider-specific Blazorise components, a type dictionary was added to the ComponentActivator, mapping the default Blazorise types to the provider-specific ones.

### CODE REVIEW

**Comment by stsrki** [comment]
It is working. But, there are several issues with this approach and it is not the way I would like it to go.

1. It is breaking change and in some way a regression of the API
2. It will not work for anyone else who implements their own IComponentActivator, see https://github.com/abpframework/abp/blob/48c52625f4c4df007f04d5ac6368b07411aa7521/framework/src/Volo.Abp.AspNetCore.Components/Volo/Abp/AspNetCore/Components/DependencyInjection/ServiceProviderComponentActivator.cs
3. Users are now forced to register their component at runtime instead of with DI at startup

I really appreciate your work and your help on this but I'm really not sure if I can accept this PR :(

**Comment by FStolte** [comment]
Fair enough, I did not think of the Use Case that users might register their own component implementations with the DI-container to replace the default components. That would make this a breaking change, indeed. 🤔

So how about this: I provide this implementation as an alternate TypeMapComponentActivator, which is off by default and can be switched on by setting a flag in the BlazoriseOptions? That way, it would not be a breaking change and would allow everyone to decide for themselves whether they'd rather have better performance or more flexibility.

**Comment by stsrki** [comment]
Yeah, I was thinking about that also but does it really make sense? It is a lot easier to create TypeMapComponentActivator in your own project and replace it within DI. The downside is that in case I register some new component in Blazorise you would also need to do the same on your side.

**Comment by FStolte** [comment]
That is definitely an option for us. But I really wonder if we're the only ones hitting this issue? We have several users that are basically working with our app from 9 to 5, so even with the ComponentActivator being transient, the memory usage for their sessions increases over the day. As a result, the overall used memory is much higher in the afternoon than it was before our update to Blazorise 0.9.3 (while it is comparable in the morning with the same amount of active sessions).

I haven't tested the impact of my new implementation in our productive system yet, but I expect that it will save another ~30% of RAM usage.

**Comment by FStolte** [comment]
@stsrki We have been running the TypeMapComponentActivator in our project for a while now and it works wonderfully. If you don't want to include it in Blazorise, I'd ask for another, smaller change that we could benefit from:

If you kept the component mapping in a Dictionary (as it is in this PR) and iterate through it in order to register the components in the ServiceCollection, then we could refer to that Dictionary in our custom ComponentActivator and would not need to maintain the mappings ourselves. If you're fine with that solution then I'll adjust this PR accordingly when I get around to it.

**Comment by stsrki** [comment]
I might consider it. But I will need to see the code first before making the last call :)

**Comment by stsrki** [comment]
Ouch, force-pushed 😅

image

What was the issue to make it?

**Comment by FStolte** [comment]
I updated the PR, now it only moves the type mappings into Dictionaries which can be used in custom ComponentActivator implementations, like our TypeMapComponentActivator.

**Comment by stsrki** [comment]
The idea looks OK although I would like it better if the list of the mapped components could be read with the same API. So instead of having `Config.AntDesignComponentMap` or `Config.BootstrapComponentMap` we could have just `Config.ComponentMap`.

Maybe have a `ComponentActivatorMap` with a dictionary of components? Or simply add a dictionary to a root Blazorise.Config?

Also, can you please open a new PR? I really hate to deal with force-push. In the past, I had problems with it and I just hate it, to say it mildly 😅

**Comment by FStolte** [comment]
No Problem, I'll create a new PR then :)

**Pull request closed without merging**
