### PR TITLE
TreeView Selected Class: Added Selected Node Class

### LINKED ISSUE #1803: TreeView: SelectedClass
Hello @stsrki 
I've also started using the Tree view for a use case I have.
I noticed that the selected class is already put there by Blazorise, In the case of bootstrap, bg-primary. 
Would be nice to just have a SelectedClass to set my own freely. Otherwise I have to endup overriding bg-primary.

### PR DESCRIPTION
**Pull request by David-Moreira**
Closes #1803

Part of #994

### CODE REVIEW

**Comment by stsrki** [comment]
Might be a good idea to also have `SelectedNodeStyle`. What do you think?

**Comment by David-Moreira** [comment]
You're right. I'll see if I have time later today to add it. 
I was also thinking if it made sense to pass in the context so people can display class or style according to additional logic. I think you do that on some places in Datagrid and it was already useful to me personally.

**Comment by stsrki** [comment]
Yeah it passed through my mind. You can add the context if you have the time.

**Comment by David-Moreira** [comment]
Yea, we better do that right away so we don't need to do breaking changes in the future.
I'll base myself on these two. These are great and enable to extend to have extra relevant properties in the future.
```
        [Parameter] public Action<TItem, DataGridRowStyling> RowStyling { get; set; }
        [Parameter] public Action<TItem, DataGridRowStyling> SelectedRowStyling { get; set; }
```

**Comment by David-Moreira** [comment]
@stsrki Done.

**Comment by stsrki** [comment]
LGTM!

Good work as usual. Thank you!

**Pull request merged**
