### PR TITLE
Column DisplayOrder

### PR DESCRIPTION
**Pull request by DDDenisSobek**
What happend:
Added `SortOrder` to `DataGridColumn` and changed `DisplayableColumns`, so that everytime `DisplayableColumns` called `Columns` will be sorted by `SortOrder`.
Documentation of `DataGrid` is extended.
Reason:
In most programms users can configurate order of columns. `SortOrder` solves this problem for `DataGrid`.

### CODE REVIEW

**Comment by stsrki** [comment]
My first thought was it something with sorting(ascending, descending). But it has more with how columns are displayed. Maybe better naming would DisplayIndex, or ColumnIndex? Or something else?

**Comment by paulosdfigueiredo** [comment]
maybe DisplayOrder ?

**Comment by stsrki** [comment]
DisplayOrder seems nice

**Comment by paulosdfigueiredo** [comment]
I edited my previous response, but looking at the PR, this will affect only Display, so DisplayOrder is ok.

**Comment by stsrki** [comment]
LGTM. Merging.

This is a good feature. Thank you!

**Comment by David-Moreira** [comment]
This one might possibly fix: 
#1435 
I have gotta test it.

**Pull request merged**
