### PR TITLE
Add model to EditTemplate context

### PR DESCRIPTION
**Pull request by Luk164**
- This commit adds model to edit template and sets it in InitEditItem inside of DataGrid.razor.cs file. This allows access to parent model of the edited value.

- Related to issue #852

### CODE REVIEW

**Comment by Luk164** [comment]
@stsrki The discussion is getting kinda off-topic in the other thread so I would like to continue our little chat here if you dont mind.

**Comment by Luk164** [comment]
@stsrki Any news? Did you find a better solution? I am technically waiting for this because one of my features requires it.

**Comment by stsrki** [comment]
I think I will go with this idea. While maybe it's not the best it is the easiest to implement and to use. But, instead of make it an `object` type I would make it a generic type as that would be better than cast every time.

Ps. Can you please base your work on dev093 branch rather than master?

**Comment by Luk164** [comment]
@stsrki Sure, I will change it right away. And sorry for the master thing, 093 did not exist yet when I created this and 092 was freshly merged.

**Comment by Luk164** [comment]
@stsrki I tried adding the types and everything broke, maybe try merging and adding it yourself? It seems the types cascade through huge amount of classes and I am not sure how everything works.

**Comment by stsrki** [comment]
Thanks, I will try to do it over the weekend if I have enough time. I'm currently doing some major refactoring/optimizations of Blazorise internals.

**Comment by Luk164** [comment]
@stsrki Once you are done, could you create a preview release? I would like to start implementing and testing some stuff and I don't want to keep switching around the libraries and nugets.

**Comment by stsrki** [comment]
Thats the plan :)

**Comment by stsrki** [comment]
Resolved with #1503. I added a new `CellEditContext<TItem>` with `Item` field that inherits from `CellEditContext`. That way there would not be any breaking changes in case someone casts context to `CellEditContext`.

I will close this PR. Also, I have added your PR to the release notes.

**Comment by Luk164** [comment]
@stsrki Can you also create that preview release nuget please? All I see at the moment on nuget repo is latest-stable (0.9.2), no previews.

**Comment by stsrki** [comment]
Sure. I will release it tomorrow during the day. I still need to finish some small things.

**Comment by Luk164** [comment]
@stsrki I can see the 0.9.2.1 release, but no preview channel for 0.9.3 (And yes I enabled the include prerelase)

**Comment by stsrki** [comment]
@Luk164 Sorry, it took me longer than expected to finish everything. It's now published on MyGet

**Comment by Luk164** [comment]
@stsrki Gotcha, just wanted to make sure. I still do not see it but it probably just needs some time to get through nuget system. I will reply again as soon as I see it appear. Thanks

**Comment by Luk164** [comment]
@stsrki Still no preview channel:

**Comment by stsrki** [comment]
It's on MyGet https://github.com/stsrki/Blazorise#try-preview

**Comment by Luk164** [comment]
@stsrki Thx, I missed that one. Is there any reason why you don't just create a preview channel on nuget?

**Comment by stsrki** [comment]
Having it on NuGet would make it harder for me since live documentation is not in sync with the preview. And there can be a lot of breaking changes between versions. This way when you get it from MyGet at least you know what you can expect.

**Comment by Luk164** [comment]
@stsrki You literally have to tick a box to even see those so I don't think it would be that big of a problem, but it's your choice

**Pull request closed without merging**
