### PR TITLE
Validation not being removed from Validations

### PR DESCRIPTION
**Pull request by peterlentine**
**Bug**
There is a bug preventing a validation from being removed from validations.
**Change**
Implemented IDisposable in the Validation class and adding a call to NotifyValidationRemoved when dispose is called.

### CODE REVIEW

**Comment by stsrki** [comment]
Hey @peterlentine, is it OK if I switch this feature to dev092 instead of sup091? I think it fits better to be in next release.

**Comment by peterlentine** [comment]
> Hey @peterlentine, is it OK if I switch this feature to dev092 instead of sup091? I think it fits better to be in next release.

I've only tested this against dev091 and sup091. I'd have to test against of dev092.

**Comment by peterlentine** [comment]
@stsrki I've tried to test my change against dev092. Unfortunately even without my change on dev092 I'm encountering a separate issue. The validators do not trigger.  I'm not sure what the issue is. If we merge this change into sup091 will it end up making it into the next release?

**Comment by peterlentine** [comment]
@stsrki Not sure what the issue is with dev092, but validation are not working at all for me there. I'm fine with this merging into dev092 in hope that it will be resolved by the time it is released. Are you cool with that?

**Comment by stsrki** [comment]
I tried to see if there is any changes on validation components but there is none. So I have no idea why it wouldn't work. From what I can see there are not that many changes in this PR. 

I will switch branch and see how it goes.

**Comment by stsrki** [comment]
Or maybe not :/

There were some conflicts after switch so I reverted to sup091. Maybe it's better to close this PR and create new one from dev092 from scratch?

**Comment by stsrki** [comment]
Closing in favor of #1269

**Pull request closed without merging**
