### PR TITLE
fix: new apis for updating chart

### PR DESCRIPTION
**Pull request by stsrki**
#792 error with charts after redrawing

This PR adds additional APIs to handle the chart update.

- AddDatasetsAndUpdate()
- AddLabelsDatasetsAndUpdate()

The problem with separate calls to chart with Clear(), AddLabel(), AddDataset() and Update() is that chartjs for some reason will raise an exception sometimes before update is called. Since it is random I cannot find the true cause. So I introduce this new APIs that will merge several calls into one operation.

### CODE REVIEW

**Comment by pmagnus2** [comment]
This fix works for one dataset. However, if we have say 5 lines displayed in one LineChart then we need multiple calls to AddDataSetsAndUpdate() and the same error occurs again. Any ideas?

**Comment by stsrki** [comment]
@pmagnus2 Can you open a new issue with the steps and code to reproduce the error?

**Comment by pmagnus2** [comment]
I will see if I can strip out a small example by the weekend. For now, the quick fix is to disable animation in the LineChartOptions by adding:
`Animation =new Animation() { Duration=0}`

**Comment by pmagnus2** [comment]
@stsrki Was not able to reproduce the error in a fresh project. Could be some other issue in my code. Will revert with new issue if it can be consistently reproduced.

**Pull request merged**
