### PR TITLE
Vertical Bar fixes

### PR DESCRIPTION
**Pull request by MitchellNZ**
Fixes issues outstanding in #1042 after PR part 1 (#1287)

- AntDesign `BarToggler` fixes
- AntDesign nested `BarDropdownMenus`
- Summary comments in code for new parameters (e.g. Bar parameter for BarToggler, etc)

### CODE REVIEW

**Comment by stsrki** [comment]
Looking good! 👍

**Comment by stsrki** [comment]
I don't see any problem so far. Is it ready for merge or do you still have some work to do?

**Comment by MitchellNZ** [comment]
It's ready to merge from my point of view!

Other Ant Design changes I think I will leave for 0.9.3 😅

**Comment by stsrki** [comment]
Merged. Can you please, once you got some time, add all the things done into #1024 ?

**Pull request merged**
