### PR TITLE
Option to hide the toggle icon in a dropdown

### PR DESCRIPTION
**Pull request by njannink**
Option to hide the arrow icon of a dropdown(toggle).

### CODE REVIEW

**Comment by WillianGruber** [comment]
Could you also implement it in the ThemeDropdown options? Directly specifying in the component should take precedence over theme, as usual. If not specified, falls back to the value in theme.

**Comment by WillianGruber** [comment]
Could you also implement it in the ThemeDropdown options? Directly specifying in the component should take precedence over theme, as usual. If not specified, falls back to the value in theme.

**Comment by njannink** [comment]
@WillianGruber added the theming support

**Comment by stsrki** [comment]
I made some optimizations 

- renamed hidden css classname to be more in line with bootstrap naming convention. 
- made new method in class provider for icon toggle visibility
- renamed ToggleIconVisible property

PS. I really like snytax for getting the default value based on theme settings `ToggleIconVisible.GetValueOrDefault( Theme?.DropdownOptions?.ToggleIconVisible ?? true )`. Nice and elegant!

**Comment by njannink** [comment]
I think it would be better if the option / theme types where `struct ` and not a `class` then you wouldn't need the null operations (?) and you could write it as:

`ToggleIconVisible.GetValueOrDefault( Theme.DropdownOptions.ToggleIconVisible )`

But that should be a different PR / refactoring

**Comment by stsrki** [comment]
Theme is not created by default so it should be able to be null. If it would be struct then there would be always some default values that would override the properties on component.

**Comment by stsrki** [comment]
Merged! Thank you!

**Pull request merged**
