### PR TITLE
Add start day of week option

### PR DESCRIPTION
**Pull request by danypellerin**
- Only for Blazorise material
- Fix for issue #1997

Was tested manually but I had issues with running E2E tests with Selenium,

### CODE REVIEW

**Comment by stsrki** [comment]
I'm not sure what to do with the feature to tell you the truth 😅

For the last couple of hours, I was refactoring DateEdit and TimeEdit to work with [flatpickr](https://flatpickr.js.org/). And DateEdit will have this feature also.

I really appreciate the effort and I would gladly accept, as it looks really good, but considering it will be overwritten I will need to close this PR. I hope that is OK? Sorry 😥

**Comment by danypellerin** [comment]
I don't see it as a problem at all. If it has this feature then it's all good for me. 👍 

It introduced me to the code and the repo and as we are planning on using this for some of our projects, I may contribute on some other things. I might request a bit of help in the Slack since I wasn't able to make Selenium run properly and I'd very much like to be able to do that next time.

**Comment by stsrki** [comment]
Thanks. When I finish the new PR can I ask you for a review? The more people test the better :)

**Comment by danypellerin** [comment]
Sure!

**Pull request closed without merging**
