### PR TITLE
Upgraded to .NET5 Preview 8

### PR DESCRIPTION
**Pull request by AhmedHemdan21**
I have upgraded the project to .NET 5 preview 8, it builds successfully, but I'm not should about the best way to test it

based on #1285

### CODE REVIEW

**Comment by stsrki** [comment]
Thanks for taking time looking into this. There are some things to consider since I already planned to do this. For start, it would be good to support multiple frameworks so that people are not forced to use .Net 5. This can be done by using `TargetFrameworks` tag.

Also, you should switch to develop branch (`dev092`). Master branch is always left clean until final release. https://github.com/stsrki/Blazorise/blob/master/CONTRIBUTING.md

**Comment by AhmedHemdan21** [comment]
@stsrki Thanks for your review, actually it's my first time to contribute and I tried to find the contributing documentation but I couldn't,
 I can have another try to support multiple frameworks if you don't mind 

would this be a valid approach to you?

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net5;</TargetFrameworks>
  </PropertyGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
    <Reference Include="old references" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net5' ">
    <Reference Include="new references" />
  </ItemGroup>
</Project>
```

**Comment by stsrki** [comment]
Yes, that's how it's usually done :)

**Comment by bfmsoft** [comment]
@stsrki you indicate above thinking of porting to .Net 5.0.  You have a timeframe?

**Comment by stsrki** [comment]
@bfmsoft I will probably do it in the during this week as part of preview version only. The official release is going to take some time.

**Comment by stsrki** [comment]
Closing this PR in favor of #1310 since the new version of .Net 5 was released in the meantime. Although it's not merged I really appreciated all the work you've done :)

**Pull request closed without merging**
