### PR TITLE
DataGrid FunctionCompiler work better with inherited members

### LINKED ISSUE #1731: DataGridColumn TItem Field does not support inherited interface types
**Describe the bug**
If TItem is type of inherited interface, it is not possible to access the fields of the base interface. 

**To Reproduce**

1. Make sure IEmployee is an inherited interface

```
public interface IPerson
    {
        int ID { get; set; }
        string Name { get; set; }
    }
    
    public interface IEmployee : IPerson 
    {
        string Organization { get; set; }
    }
```
2. Try to access a field in the base interface
`<DataGridColumn TItem="IEmployee" Field="Name" Caption="Name"  Editable="true" />`

3. Run. 
4. An exception is thrown indicating that the 'Name' field does not exist.

### PR DESCRIPTION
**Pull request by stsrki**
resolves #1731

### CODE REVIEW

**Comment by alexR148** [comment]
Thank you for the immediate solution. I will try this out.

**Comment by pvagnini** [comment]
I am having the same issue. A nested property which worked previously such as TItem="CoverPlateModel" Field="Order.CustomerID" now throws an error.

System.ArgumentException: Cannot detect the member of CoverPlate.Data.Models.CoverPlateModel (Parameter 'Order.CustomerID')
   at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafePropertyOrField(Expression item, String propertyOrFieldName)
   at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[TItem](String fieldName)

**Comment by paulosdfigueiredo** [comment]
> I am having the same issue. A nested property which worked previously such as TItem="CoverPlateModel" Field="Order.CustomerID" now throws an error.
> 
> System.ArgumentException: Cannot detect the member of CoverPlate.Data.Models.CoverPlateModel (Parameter 'Order.CustomerID')
> at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafePropertyOrField(Expression item, String propertyOrFieldName)
> at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[TItem](String fieldName)

I already submited a fix #1789

**Comment by stsrki** [comment]
It will be released with the next preview!

Guys, sorry for the inconvenience, I guess this is the price for being on the newest version 😅

**Pull request merged**
