### PR TITLE
rte - Add missing link action

### PR DESCRIPTION
**Pull request by njannink**
Missing action for creating links

### CODE REVIEW

**Comment by stsrki** [comment]
`dev092` branch is not used anymore. All new features are going to `dev093`. Can you recreate this in there?

**Comment by njannink** [comment]
its more a bugfix than a feature thats why I added it to dev092

**Comment by stsrki** [comment]
Yes, but `dev092` is unused. All bug fixes are going on `sup092`, where `sup` stands for `support`. The only reason I left dev092 is that there are still some opened PRs left.

**Comment by njannink** [comment]
Ok I missed that. I will rebase it to sup092

**Comment by njannink** [comment]
Closed will create a new PR

**Pull request closed without merging**
