### PR TITLE
Add Clicked event on toggle components

### LINKED ISSUE #2043: Add Clicked event on toggle components
**Is your feature request related to a problem? Please describe.**
I want to performa an action when a sidebar DropDownToggle item is clicked

**Describe the solution you'd like**
```
<BarDropdown>
    <BarDropdownToggle Clicked="@((visible) => LoadMarkup(visible, markUp))">
        <BarIcon IconName="FontAwesomeIcons.CropAlt" Style="font-size: 1rem;" />&nbsp;@markUp.Name
    </BarDropdownToggle>
```
### Additional context
I have tried both of the following and `they` are not called !

``` c#
@inherits Blazorise.BarDropdownToggle
@code {
    [Parameter]
    public EventCallback Clicked { get; set; }

    //protected new Task ClickHandler()
    //{
    //    Console.WriteLine(@"ClickHandler - IN");
    //    Clicked.InvokeAsync((object)null);
    //    return base.ClickHandler();
    //}

    protected override void HandleVisibilityStyles(bool visible)
    {
        Console.WriteLine(@"HandleVisibilityStyles - IN: {0}", visible);
        if (visible)
            Clicked.InvokeAsync((object)null);
        base.HandleVisibilityStyles(visible);
    }
}
```

### PR DESCRIPTION
**Pull request by stsrki**
resolves #2043 BarDropdownToggle - Can there be a Clicked handler added

### CODE REVIEW

**Comment by vip32** [comment]
very nice, just needed that :) is this part of the new 0.9.3.5 release?

**Comment by stsrki** [comment]
It is part of 0.9.4.x.previews.

Any change of the API cannot go into 0.9.3, only bug fixes.

**Comment by vip32** [comment]
yes that makes sense. Do you know a rough release ETA for 0.9.4? the [roadmap](https://github.com/stsrki/Blazorise/issues/304) didn't made that clear to me.

**Comment by stsrki** [comment]
It's hard to tell but it will take at least a month or two to finish. There are still many tickets opened for 0.9.4: https://github.com/stsrki/Blazorise/milestone/30

If you don't want to wait that long you can try preview https://github.com/stsrki/Blazorise#try-preview

**Pull request merged**
