### PR TITLE
Cache for the ThemeGenerator

### PR DESCRIPTION
**Pull request by FStolte**
This PR adds a ThemeCache for the ThemeGenerator. Whenever the generation of styles or variables for a Theme is triggered, the generator first checks if that Theme is already in the cache. If the Theme is found, the cached string is returned, otherwise it is generated and stored in the cache. If the size limit of the cache is reached, the last used Theme is removed from the cache.

The size of the cache is configurable via the BlazoriseOptions, and setting it to 0 practically deactivates the cache.

The effects of the cache are:
- For Blazor Webassembly, a Theme must only be generated the first time the user selects it. When switching between two Themes, there is a noticable delay the first time, while the change happens almost instantly after that.
- For Server-side Blazor, the benefit is even bigger since the cache is shared between all users. This means that the standard theme for a website must ideally only be generated once, which improves initial loading times for all but the first user accessing the site.

Implements #2103

### CODE REVIEW

**Comment by stsrki** [comment]
Hey, @FStolte I'm looking through the PR now and it seems like a nice improvement. The only issue I have with it is that there are many manual works required to do in `Equals` and `GetHashCode`. I know this is the problem with reference types. Now I'm thinking maybe it would be a good idea to convert all theme options classes into `record` type. It would be a lot easier to maintain and a lot easier to compare.

The main issue with records is that it is a breaking change since users would need to use it differently by using the `with` keyword to change the theme options.

What do you think of the idea?

**Comment by FStolte** [comment]
I like it 😁
I was having the same concern that the manual work for maintaining those methods might be a bit of a hassle, and a source of errors.
But I didn't even think about records as a solution for that. If you are ok with introducing a breaking change here, then I'll gladly adjust the implementation.

**Comment by stsrki** [comment]
You can try changing small parts of code into records to see if there are any issue. Also see what it means to update theme options.

We can now do:

`Theme.ColorOptions.Primary = value;`

but with records, it might be a little different. So before you work on it too much please investigate it and let me know how it goes. If it makes sense, a breaking change would not be a problem :)

**Comment by stsrki** [comment]
All theme options are now converted to `records` and I must say it works great. No need for any breaking change. I deliberately did not want them to be immutable (`get; init;`) records so that they are as easier to use as possible. The benefit now is that there is no need to manually define Equals and hash codes. It is all done by the framework.

@FStolte You can try one more time on your side and after you confirm I will merge it. Is that OK?

**Comment by stsrki** [comment]
Made some small changed and I think it is now ready for merge. If you think it needs some fixes we can do it later with new PRs.

I just want to thank you and say that you made good work with this PR!

**Pull request merged**
