### PR TITLE
DataGrid: fix double ReadData

### LINKED ISSUE #1609: Datagrid regression from 0.9.2.2 to 0.9.2.3 onwards
OnReadData is called twice with the first call not containing "filter"/"sorting" data.
```
<DataGrid TItem="PortfolioModel"
                  Data="@PortfolioList"
                  ReadData="@OnReadData"
                  PageSize="25"
                  TotalItems="@TotalPortfolio"
                  Filterable="true"
                  ShowPager="true"
                  Sortable="true"
                  Bordered="true"
                  Striped="true"
                  Hoverable="false"
                  Narrow="true"
                  Responsive="true"
                  RowSelectable=@((item)=>false)> 
... 
<DataGridColumn TItem="PortfolioModel" Field="PortfolioCode" Caption="Portfolio code" Sortable="true" Direction="SortDirection.Ascending">
</DataGrid>
```
OnReadData is called twice. In the first call, DataGridReadDataEventArgs do not contain "filter"/"sorting" data. (i.e. PortfolioCode sorting ascending)
`async Task OnReadData(DataGridReadDataEventArgs<PortfolioModel> model)`

This is working fine in version 0.9.2.2

### LINKED ISSUE #1644: BUG: in 0.9.2.4: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
Blazorise: 0.9.2.4
.NET 5.0

**How to reproduce error**
Upgrade from 0.9.1.2 to 0.9.2.4

**Solution:** 
Downgrade from 0.9.2.4 (latest) to 0.9.1.2 

------------------------------------
image

**Error**
---------------
[23:02:02 WRN] Unhandled exception rendering component: Value cannot be null. (Parameter 'element')
System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at Blazorise.Utils.ValidationAttributeHelper.GetValidationAttributes(PropertyInfo propertyInfo)
   at Blazorise.EditContextValidator.TryGetValidatableProperty(FieldIdentifier& fieldIdentifier, ValidationPropertyInfo& validationPropertyInfo, Boolean forLocalization)
   at Blazorise.EditContextValidator.ValidateField(EditContext editContext, ValidationMessageStore messages, FieldIdentifier& fieldIdentifier, Func`3 messageLocalizer)
   at Blazorise.Validation.ValidateUsingDataAnnotation(Object newValidationValue)
   at Blazorise.Validation.Validate(Object newValidationValue)
   at Blazorise.Validation.OnValidatingAll(ValidatingAllEventArgs e)
   at Blazorise.Validations.TryValidateAll()
   at Blazorise.Validations.ValidateAll()
   at ......Test.OnSubmitAsync() in .....Test.razor:line 66
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.Button.ClickHandler()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
[23:02:02 INF] Session started; Key:2af0174b-1b61-f6b3-f352-0b57f3033c03, Id:265e6e47-a84f-984d-8dc9-591bba47a17c
 

----------------

**Code**
(Removed all code except for the specific code that caused the exception error)

```
@page "/test"
@using PlatformModels.Accounts

<Validations @ref="_validations" Mode="ValidationMode.Auto" ValidateOnLoad="false" Model="@_updateAccountRequestRec">
    <Validation>
        <TextEdit @bind-Text="_dateOfBirth">
        </TextEdit>
    </Validation>
</Validations>
<Button Color="Color.Info" Float="Float.Right" Clicked="OnSubmitAsync">Submit</Button>

@code{
    private Validations _validations;

    private UpdateAccountRequest _updateAccountRequestRec = new UpdateAccountRequest();
  
    private string _dateOfBirth = string.Empty;

    private async Task OnSubmitAsync()
    {

        if (_validations.ValidateAll()) //error occurs here
        {

        }

    }

}

```

### PR DESCRIPTION
**Pull request by paulosdfigueiredo**
Moved paginationContext's events subscription from constructor into OnAfterRender to prevent them beeing triggered by the first SetParameters.

fix #1609

### CODE REVIEW

**Comment by paulosdfigueiredo** [comment]
@stsrki  This should be fix in sup092 but there's new code in this version. 

The page selector fix #1639 probably should also be merged to sup092. I don't know how you want to manage this.

**Comment by paulosdfigueiredo** [comment]
Another sugestion is to change on of the events to make them more consistent.

`[Parameter] public EventCallback<DataGridPageChangedEventArgs> PageChanged { get; set; }`
`[Parameter] public EventCallback<int> PageSizeChanged { get; set; }`

In my opinion, both should be the same type `int`.
Additionally PageChanged should be renamed CurrentPageChanged to allow _chained bind_ `@bind-CurrentPage=`

**Comment by stsrki** [comment]
Hi, thanks for the fix. I will merge it as soon as I finish another task.

Regarding the _sup092_, I'll probably just do the manual work since I cannot just cherry-pick as usual.

**Comment by paulosdfigueiredo** [comment]
Just noticed that i reference the wrong issue in my commit. Fixes 1609, not 1644.

**Comment by stsrki** [comment]
Merged! Thank you!

**Pull request merged**
