### PR TITLE
Add an event to user to paging data from any source.

### PR DESCRIPTION
**Pull request by ricardoromaobr**
Here I add an event to user to take a data to each page.

In this case the Data property is ignore to take the data.

```
<DataGrid NeedData="NeedDataToPaging">
...
</DataGrid>

void NeedDataToPaging(NeedDataEventArgs<Person> needDataEventArgs)
{
    // Previus page data
     var data = needDataEventArgs.Data;  // if for some reason you need this data
    //  The user take the responsible  to order, filter  and etc.
    var dataPage = _repository.TakeAll(needDataEventArgs.CurrentPage,
                                      needDataEventArgs.PageSize
                                      needDataEventArgs.Columns);  // information to order and filter go in it 
   
// return data to DataGrid
  needDataEventArgs.Data = dataPage.Data; 
  needDAtaEventArgs.NumberOfRows = dataPage.NumberOfRows;

}
```

With Dapper we can do it 
```

<DataGrid NeedData="TakePageWithDapper">
...
</DataGrid>

void TakePageWithDapper (NeedDataEventArgs<TITem> nde)
{
            var sql = @$"SELECT COUNT(*) FROM books
            SELECT * FROM books ORDER BY bookID 
            OFFSET {nde.StartPageRange}
            ROWS FETCH NEXT {nde.PageSize}  ROWS ONLY";

           using(var multi = connection.QueryMultiple(sql))
          {
                   nde.NumberOfRows = multi.Read<int>().Single();
                   nde.Data  = multi.Read<YourObject>().ToList();
          }

}

```

Is  not so good, but resolve the problem of our project for now.

### CODE REVIEW

**Comment by stsrki** [comment]
Hi, before I dive into your code I see that you messed with Blazorise formatting and too many changes are pushed because of that.

I have just recently add `.editorconfig` to the solution so you can get the latest version and run auto format on your files to revert them to appropriate settings.

tnx

**Comment by ricardoromaobr** [comment]
I add .editorconfig, and now?

**Comment by stsrki** [comment]
Hi @ricardoromaobr 

You need to sync/merge changes from Blazorise repository to your own repository. After you merge you will have to open `DataGrid.razor.cs` and every other file you modified. Then run `Format Document` by `Ctrl E+D` or `Ctrl K+D`, whatever the shortcut is for you.

**Comment by ricardoromaobr** [comment]
I think that is ok. I add the .editorconfig and formatted the files. One more thing to do?

**Comment by ricardoromaobr** [comment]
The save command doesn't have an event, because I'm using a database on backend, after remove the row I'll need to update database. Maybe I need another eventcallback to save data to send data to backend data. What do you think?

**Comment by stsrki** [comment]
Thank, I will take it from here. When I review it I will let you know.

**Comment by stsrki** [comment]
Instead of merging this PR would be Ok with you if use your code as a guide and implement it by myself? The problem is that you worked on `master` and I'm working on `dev088`. And they should be merged before anything can be done. And I cannot merge this PR unless everything else is resolved.

**Comment by ricardoromaobr** [comment]
Ok!

**Comment by ricardoromaobr** [comment]
When this version will be live?

**Comment by stsrki** [comment]
I really cannot give you an estimate. There are some issue that can be fixed fairly quick but some can take long time depending on the complexity whet I start to work.

You can track the progress for 0.8.8 here: https://github.com/stsrki/Blazorise/projects/8

**Comment by ricardoromaobr** [comment]
maybe a new build of the 0.87? with this new feature. I will need this in the project and I don't want to use my owner build. I want that the others time use your nuget package.

**Comment by ricardoromaobr** [comment]
Don't forget to implement my waiting feature. :)

**Comment by stsrki** [comment]
Done with #479

**Pull request closed without merging**
