### PR TITLE
DataGrid: EmptyCellTemplate

### PR DESCRIPTION
**Pull request by paulosdfigueiredo**
- Implemented EmptyCellTemplate to allow customization of all cells that are null. Updated the docs and added an EmptyCellTemplate to Datagrid Demo.
- EmptyCellTemplate is only applied if DisplayTemplate is not defined for that column.

### CODE REVIEW

**Comment by stsrki** [comment]
What happens for non-nullable types like `int` or `bool`? They are by default `0` or `false` so checking for `null `does not apply for them. Should the EmptyCellTemplate be visible for them also?

**Comment by paulosdfigueiredo** [comment]
I would say that non-nullable won't show EmptyCell. 0 and false are values that you may want to render. anyway you have the DisplayTemplate for those cases where you want different behavior.

**Comment by stsrki** [comment]
I think `EmptyCellTemplate` would make more sense to be defined inside of `DataGridColumn`. That would allow for more customization in case each column would want to be different.

**Comment by stsrki** [comment]
🤔 Now that I think about it more, a `DisplayTemplate ` could be used for more control over column `null` cells. So it's probably all good.

**Comment by stsrki** [comment]
@paulosdfigueiredo I made some changes but overall it's a good PR. Thank you!

**Comment by paulosdfigueiredo** [comment]
I had the same thoughts about adding it to columns, but has you said, there's already DisplayTemplate for those. EmptyCellTemplate should be used exactly when you want this behaviour in more than one column, without having to go through them all.

I decided not to add an Item context, but i agree that's a good thing as it adds more customization possibilities.

Keep up the good work!

**Pull request merged**
