### PR TITLE
Performance improv  only render modals child content if modal is opened

### PR DESCRIPTION
**Pull request by WillianGruber**
Hi @stsrki ,
I think it is not necessary to render the content of a modal if it is closed. I hope this also helps fix the lag in #452 .
Alternativelly, I'm rendering the iconpicker only of the modal is open.

### CODE REVIEW

**Comment by stsrki** [comment]
I will need to test this before merging. There can be problems when you remove component from rendering tree with `if `statements. When the component is removed from the tree the usual life-cycle methods will not be fired and it will skip some required init or dispose steps.

**Comment by stsrki** [comment]
@WillianGruber I just tested this and as I suspected, if we remove the modal content the usual life-cycle will not happen. In this case for example `ModalBackdrop` will dispose every time will close modal but it will NOT unregistered itself from java-script as it's reference will be null.

I think without major rewriting this PR will not work.

**Comment by WillianGruber** [comment]
I see. Sorry about that.

**Comment by stsrki** [comment]
There are so much tricks with Blazor that sometimes I wonder if it's all worth it: 😅

**Pull request closed without merging**
