### PR TITLE
feat: added IconStyle to icon component

### PR DESCRIPTION
**Pull request by stsrki**
- Added new attribute IconStyle to Icon component
- Refactored icon provider so it can detect and remove duplicate icon style names from the icon name

#343

### CODE REVIEW

**Comment by WillianGruber** [comment]
@stsrki , what is this IconStyle?
I have been working on something like this and was about to propose it, as I have already done it.

**Comment by stsrki** [comment]
It's an enum and it's used as a "suggestion" for icon styles. For example, for FontAwesome there are Solid, Regular, DuoTone. And for Material there are similar styles, Filled, Outline, Duo-Tone.

The IconStyle is just an abstraction to combine style for different icon providers.

**Comment by WillianGruber** [comment]
Ohh I see, and this won't affect my side because I use the "constants" from my custom class. Thanks.
Anyway, in a few days (maybe today) I'll present a new suggestion that you can adapt/include in Blazorise if you wish so.

**Comment by stsrki** [comment]
@WillianGruber Now that I think off. There could be a problem if icon name is "fab fa-something". It will not work as it is expecting solid "fas" style. I think I will need to fix this.

**Pull request merged**
