### PR TITLE
DataGrid - Added  SortDirectionTemplate to Column

### PR DESCRIPTION
**Pull request by paulosdfigueiredo**
Added SortDirectionTemplate to DataGridColumn to allow custom icon for sort direction.

Also fixed the cursor when a row is not sortable.

### CODE REVIEW

**Comment by paulosdfigueiredo** [comment]
Although I think it would be better to add an entire column as context, like the CaptionTemplate

`public RenderFragment<DataGridColumn<TItem>> CaptionTemplate { get; set; }`

 i just insert the SortDirection, because Column.CurrentDirection is internal and i don't know if i should change that.

**Comment by paulosdfigueiredo** [comment]
I don't know how i closed this, probably missclicked 😅.

**Comment by stsrki** [comment]
> Although I think it would be better to add an entire column as context, like the CaptionTemplate
> 
> `public RenderFragment<DataGridColumn<TItem>> CaptionTemplate { get; set; }`
> 
> i just insert the SortDirection, because Column.CurrentDirection is internal and i don't know if i should change that.

It's better this way. CurrentDirection is just for internal purposes and is not meant to be public.

**Comment by stsrki** [comment]
Tested and working fine. Thank you!

**Pull request merged**
