### PR TITLE
Add VisibleCharacters to NumericEdit

### PR DESCRIPTION
**Pull request by smokedlinq**
To support the size attribute like TextEdit.

### CODE REVIEW

**Comment by AjaxSantos** [comment]
Hey, it would be nice, if you add `VisibleCharacters` to documentation.

**Comment by smokedlinq** [comment]
@AjaxSantos -- the reason I thought this should work is because the [docs already state that this should work](https://blazorise.com/docs/components/numeric/#attributes):

> NumericEdit is just a specialized version of TextEdit component so all of the rules and styles are still working all the same. See TextEdit to find the list of supported attributes.

If you'd still like it added I will add it, let me know.

**Comment by AjaxSantos** [comment]
> 
> 
> @AjaxSantos -- the reason I thought this should work is because the [docs already state that this should work](https://blazorise.com/docs/components/numeric/#attributes):
> 
> > NumericEdit is just a specialized version of TextEdit component so all of the rules and styles are still working all the same. See TextEdit to find the list of supported attributes.
> 
> If you'd still like it added I will add it, let me know.

Oh, sorry.

**Comment by smokedlinq** [comment]
@stsrki what can I do to get this merged in?

**Comment by stsrki** [comment]
Hi @smokedlinq, sorry I'm still working on another PR that is pretty big so after I finish it I will check this and let you know.

**Comment by stsrki** [comment]
I just realized you created PR for `master` branch instead of into `dev092`. I don't allow this usually. Since this is pretty small change I will close this one and create new PR.

PS. Thanks you!

**Pull request closed without merging**
