### PR TITLE
Auto open drop down on field focus

### PR DESCRIPTION
**Pull request by jlopez788**
auto open drop down on field focus

### CODE REVIEW

**Comment by stsrki** [comment]
Hi, sorry for not getting to this sooner. Before I review this I must ask you to switch your work to the current dev branch, in this case, it's dev092. I don't allow merge into master, https://github.com/stsrki/Blazorise/blob/master/CONTRIBUTING.md

In case there is any difficulty I think the best option would be to close this PR and open new after you switch branches.

**Comment by ZYH-nb** [comment]
nb

**Comment by ZYH-nb** [comment]
> dhhd ``

**Comment by stsrki** [comment]
Closing because there were too many changes since PR is created. I also have a working version of autocomplete focus that still needs some fine-tuning to be finished.

**Pull request closed without merging**
