### PR TITLE
Added the possibility to change the page size and the position of the pager.

### PR DESCRIPTION
**Pull request by NoOneKnows92**
Added the possibility for the user to change the page size of the data grid. The pager shows now also the total amount of the datagrid items and can be placed on diffrent positions. I will do some clean up the next few days (mostly the layout of the items), but maybe somebody has a better idea about the layout of the pager.

### CODE REVIEW

**Comment by stsrki** [comment]
Hi, I can see there is a lot of formatting issues so it's hard to keep of changes. Can you please fix formatting before I review the PR?

**Comment by NoOneKnows92** [comment]
Hi, i fixed the formatting issues and tried to apply the format to my added passages aswell.

**Comment by stsrki** [comment]
I have gone through the code and must say you did a really good job. I really like how you separated the code and optimised it a little. 

There is one issue though. Open the grid page, click on `Last page` button, and then select number of rows larger than the data-source(100 or 250). The grid will empty it'self.

Other than that I don't see any other isssue.

**Comment by NoOneKnows92** [comment]
Thanks, I wasn't sure if this is the right way of expanding it, but i tried to keep the functionality and the coding style. I had looked on the bug and have fixed it, this malfunction should also appear if the filtering of the data reduces the total amount of items to less than the shown items on the last page. Hopefully this should do the trick.

**Comment by stsrki** [comment]
All good now, you did a really great job 👍

This feature is going to have special mention on release notes!. Thank you!

**Pull request merged**
