### PR TITLE
Datagrid: Multi selection improvements

### PR DESCRIPTION
**Pull request by David-Moreira**
Hello @stsrki 
I have started implementing multi select on all my grids, so I have noticed a few needed improvements.
- FilterTemplate support, for some reason I had just completely ignored it... xD I've noticed it now, that I wanted to implement a ClearFilter button right there.
- A bug on multiselectall checkbox where it would be checked when datagrid is empty.
- Not able to fully replicate the current internal multiselectall by using the MultiSelectTemplate
  - Despite the checked events being triggered, they were not correctly bound to the internals
  - Missing the new IsIndeterminate on the template

### CODE REVIEW

**Comment by stsrki** [comment]
It's weird to have two clear filter buttons 

image

**Comment by David-Moreira** [comment]
That was just to test / show example. On my grids I've removed the command column in favor of Button Row and gonna have the clear filter placed on the multi select column to take advantage of that space.

If you think that does not make sense on the demo we can remove it.

**Comment by David-Moreira** [comment]
Plus the developer can actually use the template to allocate something else on that place if he wishes.

**Comment by David-Moreira** [comment]
He could take advantage of the space to implement a drop down with custom filter options for example.
Hurray for freedom. 😅

**Comment by stsrki** [comment]
All other outstanding PRs merged for 0.9.3 and now I can focus on this.

For the most part, it looks good but I would remove an example with a duplicate clear filter button. So just remove `FilterTemplate` from multiple columns.

Also, multiple selections are not working on the Bulma demo so please look at it also.

I will postpone a new release a little until we clear these new issues.

**Comment by David-Moreira** [comment]
I'll remove the example or even just had a different one then.

I honestly did not test the other providers I just assumed it would work fine. 
I'll see if I can take a look at this asap.

**Comment by David-Moreira** [comment]
Why do you say Bulma is not working?? The check is there... it's just that it's also blue hahaha

image

**Comment by David-Moreira** [comment]
Now, I'm not sure, how this should be fixed. We have to change css somehow. Or maybe is this a theme fix on Bulma? I don't know Bulma personally.

We could add this just to the demo, it seems to only apply to Bulma, other providers seem unnaffected.
.is-checkradio[type="checkbox"] + label::after, .is-checkradio[type="checkbox"] + label:after {
    border-color: #00d1b2 !important;
}

image

Need your help on this one. Im gonna apply this fix on demo.css and finish the other correction and commit. Just tell me if you don't agree.

**Comment by stsrki** [comment]
> Why do you say Bulma is not working?? The check is there... it's just that it's also blue hahaha
> 
> image

Hahaha you're right. They're the same color 🤦‍♂️

Leave it in that case. I will need to update some table colors for Bulma once I have some time.

**Comment by David-Moreira** [comment]
Haha Alright I'll leave it then. :P

**Comment by stsrki** [comment]
> So I was going to switch the clear filter button by a reload button. That sets the CurrentPage to 1 and triggers Datagrid.reload. However, HandleReadData does not seem to be behaving correctly when you have a property attached to CurrentPage. Rings a bell as to why? Should it? Still investigating...

Maybe define it as `@bind-CurrentPage`?

**Comment by David-Moreira** [comment]
` Unhandled exception rendering component: Object of type 'Blazorise.DataGrid.DataGrid`1[[Blazorise.Demo.Pages.Tests.DataGridPage+Employee, Blazorise.Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'CurrentPageChanged'.`

**Comment by David-Moreira** [comment]
Haha it's called page has changed. Gotta write boiler plate code.
        /// <summary>
        /// Occurs after the selected page has changed.
        /// </summary>
        [Parameter] public EventCallback<DataGridPageChangedEventArgs> PageChanged { get; set; }

**Comment by stsrki** [comment]
> ` Unhandled exception rendering component: Object of type 'Blazorise.DataGrid.DataGrid`1[[Blazorise.Demo.Pages.Tests.DataGridPage+Employee, Blazorise.Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'CurrentPageChanged'.`

D**n, I was sure we had CurrentPageChanged.

> Haha it's called page has changed. Gotta write boiler plate code.
> ///
> 
> 
> /// Occurs after the selected page has changed.
> ///
> 
> [Parameter] public EventCallback PageChanged { get; set; }

API changing is in the air 😅

**Comment by David-Moreira** [comment]
Haha.
You could potentially add a CurrentPageChanged that has an EventCallBack of Int. 

The other one has a different signature, I'm not sure if you should change it?:
        /// <summary>
        /// Occurs after the selected page has changed.
        /// </summary>
        [Parameter] public EventCallback<DataGridPageChangedEventArgs> PageChanged { get; set; }

**Comment by David-Moreira** [comment]
Made the requested change. Changed the button for a reload button. I couldn't find a better icon for the reload... If you can find a better one, that'd be cool. Either way it's just an example... :P

**Comment by paulosdfigueiredo** [comment]
> > ` Unhandled exception rendering component: Object of type 'Blazorise.DataGrid.DataGrid`1[[Blazorise.Demo.Pages.Tests.DataGridPage+Employee, Blazorise.Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'CurrentPageChanged'.`
> 
> D**n, I was sure we had CurrentPageChanged.
> 
> > Haha it's called page has changed. Gotta write boiler plate code.
> > ///
> > /// Occurs after the selected page has changed.
> > ///
> > [Parameter] public EventCallback PageChanged { get; set; }
> 
> API changing is in the air 😅

https://github.com/stsrki/Blazorise/pull/1662#issuecomment-754307598 

😅

**Comment by paulosdfigueiredo** [comment]
> CurrentPageChanged



> > ` Unhandled exception rendering component: Object of type 'Blazorise.DataGrid.DataGrid`1[[Blazorise.Demo.Pages.Tests.DataGridPage+Employee, Blazorise.Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' does not have a property matching the name 'CurrentPageChanged'.`
> 
> D**n, I was sure we had CurrentPageChanged.
> 
> > Haha it's called page has changed. Gotta write boiler plate code.
> > ///
> > /// Occurs after the selected page has changed.
> > ///
> > [Parameter] public EventCallback PageChanged { get; set; }
> 
> API changing is in the air 😅

https://github.com/stsrki/Blazorise/pull/1662#issuecomment-754307598

😅

**Comment by stsrki** [comment]
@David-Moreira Looking good now. I have added some missing localization strings for command buttons and changed the reload icon. I hope we're closer to a stable release now :)

Thank you!

**Comment by David-Moreira** [comment]
Alrigjt. Can you do another rc? So I can keep testing on the project I'm working on?

**Comment by stsrki** [comment]
Yes, but first I need to finish some other task.

**Comment by David-Moreira** [comment]
Couldn't these localization be set by default inside each own Context? Thats why we created the additional New/Edit/Delete Context, so we can implement common seperate behaviour for each one of these.

image

**Comment by stsrki** [comment]
Yeah, you're right, that could be done. A little optimization.

**Comment by stsrki** [comment]
RC3 released!

**Comment by David-Moreira** [comment]
Thanks I'll update in the afternoon. I'll let you know if I find anything.

**Pull request merged**
