### PR TITLE
use components library and wwwroot files

### PR DESCRIPTION
**Pull request by Basaingeal**
Example for https://github.com/stsrki/Blazorise/issues/261

### CODE REVIEW

**Comment by Basaingeal** [comment]
This is working for me. Let me know how it works for you.

**Comment by stsrki** [comment]
I just merged `dev085` to `master` and there are some conflict. Can you fix those on your side so that PR is clean? I will test later after I publish the nugets.

**Comment by Basaingeal** [comment]
Should be better now. I haven't gone through and cleaned out the `Blazorise.Demo.Bootstrap.RC` `wwwroot` folder, although I could if you wanted, as a lot of those files are likely redundant now.

**Comment by stsrki** [comment]
I'm trying to test your branch but I'm getting merge conflicts.

image

Now I see that you have done force-push on your branch. Can you please fix merge conflicts manually without force-push?

**Comment by stsrki** [comment]
I have fixed merge conflicts and made some more changes. Later I will try to clean some more stuff for final testing.

**Comment by Basaingeal** [comment]
Sorry about that. I tend to force-push when I have to rebase a branch that has an active PR on it, since it targeted a previous commit from master than what was currently in master. But I forgot that it could cause problems for local code and should probably have done a fast-forward merge from master.

Glad to see you were able to resolve it.

**Pull request merged**
