### PR TITLE
Don't run validation if input is disabled

### LINKED ISSUE #1882: Validation is still being called when Disabled=true
Validation is still being called when Disabled=true. Is there a way to skip validation if a component is disabled? Thanks.

### PR DESCRIPTION
**Pull request by stsrki**
fixes #1882 Validation is still being called when Disabled=true

### CODE REVIEW

**Comment by David-Moreira** [comment]
@stsrki 
Wow I actually had a use case, where this was helpfull, I'm using the disabled field as a placeholder for the data that is selected somewhere else... it just started breaking that validation... xD Any ideias for workarounds?

**Comment by stsrki** [comment]
Hmm, so you want validation on a disabled field?

**Comment by stsrki** [comment]
Can you make it Readonly?

**Comment by David-Moreira** [comment]
It's basically something like this.
The disabled is usefull for the layout and automatically disabling of the field, and together with the validation stuff, I quickly bind selected stuff from Datagrid into a model with some simple frontend validation.
image

**Comment by stsrki** [comment]
I understand the scenario. But disabled inputs should not participate in validation.

Look at https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled#constraint_validation

**Comment by David-Moreira** [comment]
I see, Thanks! I'm just trying to figure out an easy workaround, so I don't have to be doing big changes now. :P

**Comment by stsrki** [comment]
Like I said, just add `ReadOnly` parameter and adjust CSS to look like a disabled input. It's how usually is done.

**Comment by David-Moreira** [comment]
I'll do that, thanks for the tip.

**Pull request merged**
