### PR TITLE
Implemented ComponentActivator

### PR DESCRIPTION
**Pull request by stsrki**
**Done**

- Removed support of netstandard2.1
- Implemented ComponentActivator class
- Remove all traces of custom component rendering
- Removed ComponentMapper
- Enabled C# 9.0 for all projects
- Removed providers `.Use()` methods from documentation
- Updated documentation and usage steps

### CODE REVIEW

**Comment by David-Moreira** [comment]
@stsrki Looks good, Way cleaner! 
Keep up the good work! 👍

**Comment by stsrki** [comment]
> @stsrki Looks good, Way cleaner! 
> Keep up the good work! 👍 

Thanks, i wanted to do this from when Blazorise was first created and just now I was finally able to do :)

**Comment by MitchellNZ** [comment]
Wooo! 🎉🎉
Great work @stsrki!
Very happy to see this change! 😁

**Comment by stsrki** [comment]
@MitchellNZ Thanks. It was 'bout time I do it 😄

**Pull request merged**
